version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  #app:
  #  build:
  #    context: .
  #    target: production
  #  ports:
  #    - 3001:3001
  #  command: npm run start:prod
  #  depends_on:
  #    - db

volumes:
  db_data:
